// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agodijuyujiliengmail.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2RpanV5dWppbGllbmdtYWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjcwMzIsImV4cCI6MjA3MTU0MzAzMn0.zdZgTihlA-k3JLxG4iNTmvSg4eolTT7vJZ4UHSENxYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});